# Generated by Django 3.2.7 on 2021-09-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mausic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'music', 'verbose_name_plural': 'musics'},
        ),
        migrations.AlterModelOptions(
            name='singer',
            options={'verbose_name': 'Singer', 'verbose_name_plural': 'Singers'},
        ),
    ]
