# Generated by Django 3.2.7 on 2021-09-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mausic', '0002_auto_20210923_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='size',
            field=models.FloatField(),
        ),
    ]
